
language: csharp
solution: dangobot.sln

install:
  - nuget restore dangobot.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release dangobot.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./dangobot.tests/bin/Release/dangobot.tests.dll
